Create database  mydatabase;
Use mydatabase;
show tables;
SELECT * FROM Customer_Analysis LIMIT 20;

# Q1. What is the total revenue generated by male vs female customer?
select gender , sum(purchase_amount) as revenue
from customer_Analysis
group by gender;

#Q2.  Which customers used a discount but still spent more than the average purchase amount?
select customer_id , purchase_amount
from customer_analysis
where discount_applied = 'Yes' and purchase_amount >=(select avg(purchase_amount) from customer_analysis)

#Q3.Which are the top 5 products with the highest average review rating?
select item_purchased,Round(Avg(review_rating),2) As avg_rating
from customer_analysis
group by item_purchased
order by avg_rating desc
limit 5;

 #Q4.  Compare the average Purchase Amounts between Standard and Express Shipping?
 select shipping_type,
 avg(purchase_amount)
 from customer_analysis
 where shipping_type in ('Standard' ,'Express')
 group by shipping_type
#Q5. Do subscribed customer spend more? Compare average spend and total revenue between subscribes and non-subscribers.
  
  
  select subscription_status,
  count(customer_id) as total_customers,
  Round(Avg(purchase_amount),2) as avg_spend,
  Round(Sum(purchase_amount),2) as total_revenue
  from customer_analysis
  group by subscription_status;
  
#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased ,
round(100*sum(Case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer_analysis
group by item_purchased 
order by discount_rate desc
limit 5;

#Q7. Segment customer into New, Returning , and Loyal based on their total number of previous purchase, and show the count of each segment.
SELECT 
    customer_segment,
    COUNT(*) AS total_customers
FROM (
    SELECT 
        customer_id,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_analysis
) t
GROUP BY customer_segment;



#Q8. What are the top 3 most purchased products with in each category?
SELECT 
    category,
    item_purchased,
    COUNT(customer_id) AS total_orders
FROM customer_analysis
GROUP BY category, item_purchased
ORDER BY category, total_orders DESC;


  #Q9. Are customer who are repeat buyers (more than 5 previous purchase) also likely to subscribe?
  select subscription_status,
  count(customer_id) as repeat_buyers
  from customer_analysis
  where previous_purchases > 5
  group by subscription_status;
  
  
  #Q10. What is the revenue contribution of each age group?
select age_group,
  sum(purchase_amount) as total_revenue
  from customer_analysis
  group by age_group
  order by   total_revenue desc;